# Generated by Django 5.1.6 on 2025-02-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$2kMdOJVtuGKPuMQMx4aeD6$LV07k89gNTjZGtiCQMDBxZmia1IeFWq0gzSlHMGe34k=', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
