# Generated by Django 5.1.6 on 2025-02-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_password_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$D3pZuc5Lx1W1QLui9T4TBs$gul78lg5Silki7hhASnDR5TdYB+/bHHHPuvTQYJUdDM=', max_length=255),
        ),
    ]
